SELECT TEAM_ID AS 팀ID, COUNT(*) AS 인원수
FROM PLAYER
GROUP BY TEAM_ID
HAVING TEAM_ID IN ('K02', 'K09')

SELECT POSITION AS 포지션, AVG(HEIGHT) AS 평균키
FROM PLAYER
GROUP BY POSITION
HAVING MAX(HEIGHT) >= 190

SELECT TEAM_ID,
ISNULL(SUM (CASE WHEN POSITION = 'FW' THEN 1 END), 0) AS FW
FROM PLAYER
GROUP BY TEAM_ID 

SELECT TEAM_ID,
ISNULL(SUM(CASE WHEN POSITION = 'FW' THEN 1 END), 0) AS FW,
ISNULL(SUM(CASE WHEN POSITION = 'MF' THEN 1 END), 0) AS MF,
ISNULL(SUM(CASE WHEN POSITION = 'DF' THEN 1 END), 0) AS DF,
COUNT(*) AS SUM
FROM PLAYER
GROUP BY TEAM_ID

SELECT PLAYER_NAME AS 선수명, POSITION 포지션, BACK_NO 백넘버
FROM PLAYER
WHERE BACK_NO IS NOT NULL
ORDER BY 3 DESC, 2, 1

USE COMPANY;

SElect job, count(*) as 인원수, avg(sal) as 평균급여
from emp
group by job
having avg(sal)>2500
order by avg(sal) desc

select empno, ename
from emp
order by mgr