BEGIN TRAN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT SUM(PRICE) 총액
FROM BOOK;

SELECT SUM(PRICE) 총액
FROM BOOK;

COMMIT;

-- REPEATABLE READ로 하면 팬텀 읽기 모드 발생
-- SERIALIZABLE 레벨로 바꿔주면 됨.